name: CI Test - Main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: baixar os fontes
        uses: actions/checkout@v3

      - name: usar node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: configurar npm par usar deduplicacao
        run: npm config set prefer-dedupe true

      - name: instalar dependencias
        run: npm ci

      - name: script build
        run: npm run build --if-present

      - name: executar testes
        run: npm test
